version :  "3"
services:
        python-container:
                build:
                      context: .
                      dockerfile: Dockerfile.txt
                ports:
                        - 8080:80
